Repository wecode-bootcamp-korea/13-DEV101-backend, pull requests merged in 2020-11, with the labels that each got.

#3 Add: added product app
  dev101/settings.py
  dev101/urls.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
Labels: Status: Accepted

#4 Add: added user app
  dev101/settings.py
  product/models.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청

#5 Add: added order app
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  product/migrations/0002_auto_20201104_1542.py
  user/migrations/0002_auto_20201104_1542.py
  user/models.py
Labels: Status: 리뷰 요청

#6 Edit: edited models
  product/migrations/0003_auto_20201104_1701.py
  product/migrations/0004_auto_20201104_2130.py
  product/migrations/0005_classtag_name.py
  product/migrations/0006_auto_20201105_1444.py
  product/migrations/0007_auto_20201105_1449.py
  product/migrations/0008_auto_20201105_1747.py
  product/models.py
  user/migrations/0003_user_cheer_point.py
  user/migrations/0004_auto_20201105_0915.py
  user/models.py
Labels: Status: 리뷰 요청

#8 Add: added product detail view & post's comment view with unit test
  .gitignore
  dev101/urls.py
  product/migrations/0009_review_created_at.py
  product/migrations/0010_post_image_url.py
  product/migrations/0011_comment_image_url.py
  product/migrations/0012_auto_20201108_2210.py
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
  user/migrations/0005_auto_20201106_1701.py
  user/migrations/0006_auto_20201106_1816.py
  user/models.py
Labels: Status: 리뷰 요청

#11 Edit: edited user model
  user/models.py
Labels: Status: 리뷰 요청

#10 Add : user/url , user/views SignUpView&SignInView, utils.py, mypage 생성
  db_uploader.py
  dev101/settings.py
  dev101/urls.py
  user/tests.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#12 Edit: edited user model & migrated
  user/migrations/0007_auto_20201109_2155.py
  user/migrations/0008_auto_20201110_1328.py
  user/models.py
Labels: Status: 리뷰 요청

#13 Add : user tests.py
  user/tests.py
Labels: Status: 리뷰 요청

#14 Add: added product like view & gitignore & edited url & comment view
  dump.rdb
  product/tests.py
  product/urls.py
  product/views.py
Labels: Status: 리뷰 요청

#15 Add: added product package view & unit test
  product/tests.py
  product/urls.py
  product/views.py
Labels: Status: Accepted

#20 Edit: edited products view planned data(#17보다 먼저 머지 부탁드립니다)
  product/views.py
Labels: Status: 리뷰 요청

#16 Add : user/url , user/view, tests 완료
  product/tests.py
  product/urls.py
  product/views.py
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청

#17 Add: add order view & 문자인증 & unit test
  dev101/settings.py
  dev101/urls.py
  order/migrations/0001_initial.py
  order/migrations/0002_smsauth.py
  order/migrations/0003_order_total_price.py
  order/models.py
  order/tests.py
  order/urls.py
  order/views.py
Labels: Status: 리뷰 요청

#18 Add : creator/basic_info view
  dev101/settings.py
  user/models.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#19 Add: added product cheer view & unit test
  .gitignore
  dump.rdb
  product/tests.py
  product/urls.py
  product/views.py
Labels: Status: 리뷰 요청
